from Route import Route

routes = [
	Route("Boston", "Miami", 12),
	Route("Calgary", "Phoenix", 13),
	Route("Calgary", "Salt Lake City", 7),
	Route("Chicago", "New Orleans", 7),
	Route("Chicago", "Santa Fe", 9),
	Route("Dallas", "New York", 11),
	Route("Denver", "El Paso", 4),
	Route("Denver", "Pittsburgh", 11),
	Route("Duluth", "El Paso", 10),
	Route("Duluth", "Houston", 8),
	Route("Helena", "Los Angeles", 8),
	Route("Kansas City", "Houston", 5),
	Route("Los Angeles", "Chicago", 16),
	Route("Los Angeles", "Miami", 20),
	Route("Los Angeles", "New York", 21),
	Route("Montreal", "Atlanta", 9),
	Route("Montreal", "New Orleans", 13),
	Route("New York", "Atlanta", 6),
	Route("Portland", "Nashville", 17),
	Route("Portland", "Phoenix", 11),
	Route("San Francisco", "Atlanta", 17),
	Route("Sault St. Marie", "Nashville", 8),
	Route("Sault St. Marie", "Oklahoma City", 9),
	Route("Seattle", "Los Angeles", 9),
	Route("Seattle", "New York", 22),
	Route("Toronto", "Miami", 10),
	Route("Vancouver", "Montreal", 20),
	Route("Vancouver", "Santa Fe", 13),
	Route("Winnipeg", "Houston", 12),
	Route("Winnipeg", "Little Rock", 11),

]